### ISSUE TITLE
All files in one directory

### ISSUE THREAD

**Issue by wiebereu** [avibrazil/picard-scripting#1]
Hi I use your script for file naming, but i found out that when i check an artist with different albums, all the songs are in one folder and the subfolders (albums) are empty. 

What i was looking for is one folder with the name of the Artist and in that folder all albums of that artist in subsequent subfolders. 
That is not what i got from the scripts. 
![Picard file naming](https://github.com/avibrazil/picard-scripting/assets/58167538/76ff44ad-ee0f-48ce-bbea-c63d0a3fb2ab)
![Picard file naming 2](https://github.com/avibrazil/picard-scripting/assets/58167538/1c1f0375-d3b5-42d4-aea0-b6ce853e18ab)

I upload 2 examples to show you what i mean. 

By the way the script i use is not the latest script from you

**Comment by wiebereu** [comment]
The sub directories Greatest Hits Disc 1 and 2 are empty.

**Comment by avibrazil** [comment]
Files on your screenshot doesn’t seem to be organized by my scripts. This is how Depeche Mode discography looks like when handled by my scripts. It’s one folder per album, all under one artist folder. Multi-disc albums (as the Beatles’ White Album in image) has tracks named accordingly.

<img width="404" alt="Screenshot 2023-06-29 at 09 58 34" src="https://github.com/avibrazil/picard-scripting/assets/3484242/dfcc86f1-775b-4162-a942-a09f35851329">
